on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Debug APKs
        run: ./gradlew --no-daemon assembleDebug
      - name: Build Release APKs
        run: ./gradlew --no-daemon assembleRelease
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.main_project_module }}/build/outputs/apk/debug/app-debug.apk
            ${{ env.main_project_module }}/build/outputs/apk/release/app-release.apk
  

    
