on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Debug APKs
        run: ./gradlew --no-daemon assembleDebug
      - name: Build Release APKs
        run: ./gradlew --no-daemon assembleRelease
  
