on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Debug APKs
        run: ./gradlew --no-daemon assembleDebug
      - name: Build Release APKs
        run: ./gradlew --no-daemon assembleRelease
      - uses: Tlaster/android-sign@v1
        name: Sign app APK
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: build/release/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            build/release/signed/app-release.apk
  

    
